#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

# Initialize a counter
count=0

# Use a while loop to display "Best School" 10 times
while [ $count -lt 10 ]; do
    echo "Best School"
    ((count++))
done
